from __future__ import annotations

from dataclasses import dataclass, field
import html
from typing import Any

import folium
from research.network_loader import NetworkBundle


Coordinate = tuple[float, float]  # (longitude, latitude)


@dataclass
class RouteLayer:
    route: list[str]
    route_coordinates: list[Coordinate]
    ground_truth: list[str] | None = None
    ground_truth_coordinates: list[Coordinate] | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    color: str = "blue"
    ground_truth_color: str = "green"
    missing_route_nodes: list[str] = field(default_factory=list)
    missing_ground_truth_nodes: list[str] = field(default_factory=list)


@dataclass
class SegmentHighlight:
    from_node: str
    to_node: str
    coordinates: list[Coordinate]
    status: str
    color: str
    weight: int = 7
    opacity: float = 0.95
    dash_array: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


def node_coordinates_from_network_bundle(
    bundle: NetworkBundle,
) -> dict[str, Coordinate]:
    """Extract node coordinates from a loaded NetworkBundle graph.

    Coordinates are read from SSAL edge attributes generated by the research
    network loader. Returned coordinates use (longitude, latitude).
    """
    coordinates: dict[str, Coordinate] = {}

    for source, edges in bundle.graph.adjacency.items():
        for edge in edges:
            attrs = edge.attrs or {}

            from_x = attrs.get("from_x")
            from_y = attrs.get("from_y")
            to_x = attrs.get("to_x")
            to_y = attrs.get("to_y")

            if from_x is not None and from_y is not None:
                coordinates[source] = (float(from_x), float(from_y))

            if to_x is not None and to_y is not None:
                coordinates[edge.target] = (float(to_x), float(to_y))

    return coordinates


class RouteVisualization:
    """Folium-based route visualization interface for node-ID routes.

    The visualizer accepts routes as node-ID lists and resolves coordinates from
    a provided node-coordinate mapping. It intentionally does not parse model
    responses or validate route correctness; the evaluator owns that logic.
    """

    def __init__(
        self,
        node_coordinates: dict[str, Coordinate],
        metadata: dict[str, Any] | None = None,
        tiles: str | None = None,
        strict_coordinates: bool = False,
    ):
        self.node_coordinates = node_coordinates
        self.metadata = metadata or {}
        self.tiles = tiles
        self.strict_coordinates = strict_coordinates
        self.routes: list[RouteLayer] = []
        self.segment_highlights: list[SegmentHighlight] = []

    def add_route(
        self,
        route: list[str],
        *,
        ground_truth: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
        color: str = "blue",
        ground_truth_color: str = "green",
    ) -> None:
        route_coordinates, missing_route_nodes = self._resolve_coordinates(
            route,
            label="route",
        )

        ground_truth_coordinates = None
        missing_ground_truth_nodes: list[str] = []

        if ground_truth is not None:
            (
                ground_truth_coordinates,
                missing_ground_truth_nodes,
            ) = self._resolve_coordinates(
                ground_truth,
                label="ground truth",
            )

        self.routes.append(
            RouteLayer(
                route=route,
                route_coordinates=route_coordinates,
                ground_truth=ground_truth,
                ground_truth_coordinates=ground_truth_coordinates,
                metadata=metadata or {},
                color=color,
                ground_truth_color=ground_truth_color,
                missing_route_nodes=missing_route_nodes,
                missing_ground_truth_nodes=missing_ground_truth_nodes,
            )
        )

    def add_segment_highlight(
        self,
        *,
        from_node: str,
        to_node: str,
        status: str,
        color: str,
        metadata: dict[str, Any] | None = None,
        dash_array: str | None = None,
        weight: int = 7,
        opacity: float = 0.95,
    ) -> None:
        """Add one highlighted segment overlay by node IDs.

        If both endpoints have coordinates, the highlight renders as a line.
        If only one endpoint has coordinates, it renders as a warning marker.
        If neither endpoint has coordinates, it is skipped.
        """
        coordinates = self._resolve_partial_segment_coordinates(
            from_node=from_node,
            to_node=to_node,
        )

        if not coordinates:
            return

        self.segment_highlights.append(
            SegmentHighlight(
                from_node=from_node,
                to_node=to_node,
                coordinates=coordinates,
                status=status,
                color=color,
                weight=weight,
                opacity=opacity,
                dash_array=dash_array,
                metadata=metadata or {},
            )
        )

    def _resolve_partial_segment_coordinates(
        self,
        *,
        from_node: str,
        to_node: str,
    ) -> list[Coordinate]:
        """Resolve coordinates for one segment, skipping missing endpoints."""
        coords: list[Coordinate] = []

        if from_node in self.node_coordinates:
            coords.append(self.node_coordinates[from_node])

        if to_node in self.node_coordinates:
            coords.append(self.node_coordinates[to_node])

        return coords

    def _resolve_coordinates(
        self,
        route: list[str],
        *,
        label: str,
    ) -> tuple[list[Coordinate], list[str]]:
        missing_nodes = [
            node_id for node_id in route if node_id not in self.node_coordinates
        ]

        if missing_nodes and self.strict_coordinates:
            raise ValueError(f"Missing coordinates for {label} nodes: {missing_nodes}")

        coordinates = [
            self.node_coordinates[node_id]
            for node_id in route
            if node_id in self.node_coordinates
        ]

        return coordinates, missing_nodes

    def _format_metadata_html(self, metadata: dict[str, Any], title: str) -> str:
        """Format metadata as a small HTML table for Folium popups/tooltips."""
        escaped_title = html.escape(str(title))

        if not metadata:
            return f"<b>{escaped_title}</b>"

        rows = []
        for key, value in metadata.items():
            escaped_key = html.escape(str(key))
            escaped_value = html.escape(str(value))
            rows.append(
                "<tr>"
                f"<td style='padding-right: 8px; font-weight: bold;'>{escaped_key}:</td>"
                f"<td>{escaped_value}</td>"
                "</tr>"
            )

        return (
            f"<b>{escaped_title}</b><br>"
            "<table style='width: 100%; border-collapse: collapse; font-size: 12px;'>"
            + "".join(rows)
            + "</table>"
        )

    def _map_bounds_points(self) -> tuple[list[float], list[float]]:
        """Return latitude and longitude lists used for map centering/bounds."""
        all_lats: list[float] = []
        all_lons: list[float] = []

        for layer in self.routes:
            for lon, lat in layer.route_coordinates:
                all_lats.append(lat)
                all_lons.append(lon)

            if layer.ground_truth_coordinates:
                for lon, lat in layer.ground_truth_coordinates:
                    all_lats.append(lat)
                    all_lons.append(lon)

        for highlight in self.segment_highlights:
            for lon, lat in highlight.coordinates:
                all_lats.append(lat)
                all_lons.append(lon)

        if not all_lats and self.node_coordinates:
            all_lats = [lat for lon, lat in self.node_coordinates.values()]
            all_lons = [lon for lon, lat in self.node_coordinates.values()]

        return all_lats, all_lons

    def _add_ground_truth_layer(
        self,
        *,
        route_map: folium.Map,
        layer: RouteLayer,
        label: str,
    ) -> None:
        """Add the ground-truth route as a separate toggleable layer."""
        if not layer.ground_truth_coordinates:
            return

        ground_truth_group = folium.FeatureGroup(name=f"{label} · ground truth")
        ground_truth_lat_lons = [
            (lat, lon) for lon, lat in layer.ground_truth_coordinates
        ]

        folium.PolyLine(
            locations=ground_truth_lat_lons,
            color=layer.ground_truth_color,
            weight=6,
            opacity=0.6,
            dash_array="10",
            tooltip=folium.Tooltip(f"<b>Ground Truth:</b> {label}"),
        ).add_to(ground_truth_group)

        ground_truth_group.add_to(route_map)

    def _add_candidate_layer(
        self,
        *,
        route_map: folium.Map,
        layer: RouteLayer,
        label: str,
        tooltip_html: str,
    ) -> None:
        """Add the candidate route as a separate toggleable layer."""
        candidate_group = folium.FeatureGroup(name=f"{label} · candidate")
        route_lat_lons = [(lat, lon) for lon, lat in layer.route_coordinates]

        if route_lat_lons:
            folium.PolyLine(
                locations=route_lat_lons,
                color=layer.color,
                weight=4,
                opacity=0.8,
                tooltip=folium.Tooltip(tooltip_html),
            ).add_to(candidate_group)

            folium.CircleMarker(
                location=route_lat_lons[0],
                radius=5,
                color="green",
                fill=True,
                fill_color="green",
                tooltip=f"Start: {layer.route[0]}",
            ).add_to(candidate_group)

            folium.CircleMarker(
                location=route_lat_lons[-1],
                radius=5,
                color="red",
                fill=True,
                fill_color="red",
                tooltip=f"End: {layer.route[-1]}",
            ).add_to(candidate_group)

        if layer.missing_route_nodes or layer.missing_ground_truth_nodes:
            missing_metadata = {
                "missing route nodes": ", ".join(layer.missing_route_nodes) or "—",
                "missing ground truth nodes": (
                    ", ".join(layer.missing_ground_truth_nodes) or "—"
                ),
            }
            missing_html = self._format_metadata_html(
                missing_metadata,
                f"Missing coordinates: {label}",
            )
            # Add a small warning marker at the first visible route point,
            # or map center when no route point could be resolved.
            marker_location = (
                route_lat_lons[0]
                if route_lat_lons
                else route_map.location
            )
            folium.Marker(
                location=marker_location,
                tooltip=folium.Tooltip(missing_html),
                icon=folium.Icon(color="orange", icon="warning-sign"),
            ).add_to(candidate_group)

        candidate_group.add_to(route_map)

    def _add_segment_highlight_layer(self, route_map: folium.Map) -> None:
        """Add segment highlights as a separate toggleable layer."""
        if not self.segment_highlights:
            return

        highlight_group = folium.FeatureGroup(name="Segment highlights")

        for highlight in self.segment_highlights:
            lat_lons = [(lat, lon) for lon, lat in highlight.coordinates]

            tooltip_html = self._format_metadata_html(
                {
                    "status": highlight.status,
                    **highlight.metadata,
                },
                f"{highlight.from_node} → {highlight.to_node}",
            )

            if len(lat_lons) >= 2:
                folium.PolyLine(
                    locations=lat_lons,
                    color=highlight.color,
                    weight=highlight.weight,
                    opacity=highlight.opacity,
                    dash_array=highlight.dash_array,
                    tooltip=folium.Tooltip(tooltip_html),
                ).add_to(highlight_group)

            elif len(lat_lons) == 1:
                folium.CircleMarker(
                    location=lat_lons[0],
                    radius=6,
                    color=highlight.color,
                    fill=True,
                    fill_color=highlight.color,
                    tooltip=folium.Tooltip(tooltip_html),
                ).add_to(highlight_group)

        highlight_group.add_to(route_map)

    def render(self, save_path: str | None = None) -> folium.Map:
        """Render the map with added route layers and segment highlights."""
        all_lats, all_lons = self._map_bounds_points()

        if all_lats and all_lons:
            center_lat = sum(all_lats) / len(all_lats)
            center_lon = sum(all_lons) / len(all_lons)
            route_map = folium.Map(
                location=[center_lat, center_lon],
                zoom_start=15,
                tiles=self.tiles,
            )
            route_map.fit_bounds(
                [[min(all_lats), min(all_lons)], [max(all_lats), max(all_lons)]]
            )
        else:
            route_map = folium.Map(location=[0, 0], zoom_start=2, tiles=self.tiles)

        if self.metadata:
            network_info = self._format_metadata_html(self.metadata, "Network Metadata")

            fixed_html = f"""
            <div style="
                position: fixed;
                bottom: 50px;
                left: 50px;
                width: 250px;
                background-color: white;
                padding: 10px;
                border: 2px solid black;
                border-radius: 5px;
                z-index: 9999;
                opacity: 0.8;
            ">
                {network_info}
            </div>
            """
            route_map.get_root().html.add_child(folium.Element(fixed_html))

        for index, layer in enumerate(self.routes, start=1):
            label = layer.metadata.get("label", f"Route {index}")
            label = str(label)
            tooltip_html = self._format_metadata_html(layer.metadata, label)

            self._add_ground_truth_layer(
                route_map=route_map,
                layer=layer,
                label=label,
            )
            self._add_candidate_layer(
                route_map=route_map,
                layer=layer,
                label=label,
                tooltip_html=tooltip_html,
            )

        self._add_segment_highlight_layer(route_map)

        folium.LayerControl().add_to(route_map)

        if save_path:
            route_map.save(save_path)

        return route_map

    def render_html(self) -> str:
        """Render the map as an HTML string for Streamlit embedding."""
        return self.render().get_root().render()
